//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomSquadCreater.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SquadContext : DbContext
    {
        public SquadContext()
            : base("name=SquadContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mails> Mails { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Score> Score { get; set; }
    }
}
