//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomSquadCreater.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public string PlayerSurname { get; set; }
        public string PlayerEmail { get; set; }
        public Nullable<int> PlayerPower { get; set; }
        public string PlayerImageUrl { get; set; }
        public string PlayerPosition { get; set; }
        public string PlayerPassword { get; set; }
        public string PlayerUserName { get; set; }
        public Nullable<bool> PlayerIsComing { get; set; }
        public Nullable<System.DateTime> PlayerVoteDate { get; set; }
        public Nullable<bool> PlayerIsOnline { get; set; }
        public string PlayerConnectionId { get; set; }
        public Nullable<System.DateTime> PlayerLastLoginTime { get; set; }
    }
}
